"""Regenerate the active Jounieh curb at 3x from the preserved 1x curb.

The input is immutable provenance; rerunning this script cannot scale twice.
Trajectory coordinates are regenerated by prepare_for_calibration.py.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "_source_1x" / "Jounieh_Road_Boundaries_extended_1x.csv"
TARGET = HERE / "Jounieh_Road_Boundaries.csv"
FACTOR = 3.0
SOURCE_METRES_PER_PIXEL = 0.04354578


def main() -> None:
    if not SOURCE.is_file():
        raise FileNotFoundError(f"Preserved 1x curb is required: {SOURCE}")
    curb = pd.read_csv(SOURCE)
    for column in ("x", "y", "buffer_m"):
        curb[column] *= FACTOR
    curb["area_m2"] *= FACTOR ** 2
    curb["m_per_px"] = SOURCE_METRES_PER_PIXEL * FACTOR
    temp = TARGET.with_suffix(".csv.tmp")
    curb.to_csv(temp, index=False)
    temp.replace(TARGET)
    manifest = {
        "source": SOURCE.name,
        "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "target": TARGET.name,
        "target_sha256": hashlib.sha256(TARGET.read_bytes()).hexdigest(),
        "coordinate_factor": FACTOR,
        "metres_per_pixel": SOURCE_METRES_PER_PIXEL * FACTOR,
        "area_factor": FACTOR ** 2,
    }
    (HERE / "scale_3x_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
